name: peas_cloud
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.2
  firebase_auth: ^3.3.0
  firebase_messaging: ^11.2.0
  firebase_storage: ^10.2.0
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

